kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-reader
rules:
- apiGroups: [""]
  resources: ["nodes", "nodes/status"] # might be able to pair this down to just nodes
  verbs: ["get", "watch", "list"]      # might be able to pair this down